spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.249.129:8848
    gateway:
      routes:
        - id: myoj-backend-user-service
          uri: lb://myoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: myoj-backend-question-service
          uri: lb://myoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: myoj-backend-judge-service
          uri: lb://myoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: myoj-backend-comment-service
          uri: lb://myoj-backend-comment-service
          predicates:
            - Path=/api/comment/**
  redis:
    host: 192.168.249.129
    port: 6379
    password: adgjl08642
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  application:
    name: myoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2